services:
  - type: web
    name: cakephp-app
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "mysql://username:password@hostname:port/database"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
